# Project - Data Cleaning

## Introduction
In this lab, we'll make use of everything we've learned about pandas, data cleaning, and Exploratory Data Analysis. In order to complete this lab, you'll have to make import, clean, combine, reshape, and visualize data to answer questions provided, as well as your own questions!

## Objectives
You will be able to:
* Show mastery of the content covered in this section

## The Dataset
In this lab, we'll work with the comprehensive [Super Heroes Dataset](https://www.kaggle.com/claudiodavi/superhero-set/data), which can be found on Kaggle!

## Goals
* Use all available pandas knowledge to clean the dataset and deal with null values
* Use Queries and aggregations to group the data into interesting subsets as needed
* Use descriptive statistics and data visualization to find answers to questions we may have about the data. 

## Getting Started

In the cell below:

* Import and alias pandas as `pd`
* Import and alias numpy as `np`
* Import and alias seaborn as `sns`
* Import and alias matplotlib.pyplot as `plt`
* Set matplotlib visualizations to display inline in the notebook

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

For this lab, our dataset is split among two different sources--`heroes_information.csv` and `super_hero_powers.csv`.

Use pandas to read in each file and store them in DataFrames in the appropriate variables below. Then, display the head of each to ensure that everything loaded correctly.

In [2]:
heroes_df = pd.read_csv('heroes_information.csv')
powers_df = pd.read_csv('super_hero_powers.csv')

In [3]:
heroes_df.head()

,Unnamed: 0,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0
1,1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0
4,4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0

In [4]:
powers_df.head()

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

It looks as if the heroes information dataset contained an index column.  We did not specify that this dataset contained an index column, because we hadn't seen it yet. Pandas does not know how to tell apart an index column from any other data, so it stored it with the column name `Unnamed: 0`.  

Our DataFrame provided row indices by default, so this column is not needed.  Drop it from the DataFrame in place in the cell below, and then display the head of `heroes_df` to ensure that it worked properly.

In [5]:
heroes_df = heroes_df.drop('Unnamed:0', axis = 1, inplace = True)

KeyError: "['Unnamed:0'] not found in axis"

In [6]:
heroes_df.head()

,Unnamed: 0,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0
1,1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0
4,4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0

## Familiarize Yourself With the Dataset

The first step in our Exploratory Data Analysis will be to get familiar with the data.  This step includes:

* Understanding the dimensionality of your dataset
* Investigating what type of data it contains, and the data types used to store it
* Discovering how missing values are encoded, and how many there are
* Getting a feel for what information it does and doesn't contain

In the cell below, get the descriptive statistics of each DataFrame.

In [7]:
display(heroes_df.describe())

       Unnamed: 0      Height      Weight
count  734.000000  734.000000  732.000000
mean   366.500000  102.254087   43.855191
std    212.031837  139.624543  130.823733
min      0.000000  -99.000000  -99.000000
25%    183.250000  -99.000000  -99.000000
50%    366.500000  175.000000   62.000000
75%    549.750000  185.000000   90.000000
max    733.000000  975.000000  900.000000

In [8]:
powers_df.describe()

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
count,667,667,667,667,667,667,667,667,667,667,...,667,667,667,667,667,667,667,667,667,667
unique,667,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,Niki Sanders,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,1,425,489,656,642,620,410,541,590,455,...,653,651,665,658,666,666,666,665,665,665

In [9]:
display(powers_df.describe())

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
count,667,667,667,667,667,667,667,667,667,667,...,667,667,667,667,667,667,667,667,667,667
unique,667,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,Niki Sanders,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,1,425,489,656,642,620,410,541,590,455,...,653,651,665,658,666,666,666,665,665,665

## Dealing with Null Values

Starting in the cell below, detect and deal with any null values in either data frame.  Then, explain your methodology for detecting and dealing with outliers in the markdown section below.  Be sure to explain your strategy for dealing with null values in numeric columns, as well as your strategy for dealing with null values in non-numeric columns.  

Note that if you need to add more cells to write code in, you can do this by:

**1.** Highlighting a cell and then pressing `ESC` to enter command mode.  
**2.** Press `A` to add a cell above the highlighted cell, or `B` to add a cell below the highlighted cell. 

Describe your strategy below this line:
____________________________________________________________________________________________________________________________

In [14]:
heroes_df

,Unnamed: 0,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0
1,1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0
4,4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0
5,5,Absorbing Man,Male,blue,Human,No Hair,193.0,Marvel Comics,-,bad,122.0
6,6,Adam Monroe,Male,blue,-,Blond,-99.0,NBC - Heroes,-,good,-99.0
7,7,Adam Strange,Male,blue,Human,Blond,185.0,DC Comics,-,good,88.0
8,8,Agent 13,Female,blue,-,Blond,173.0,Marvel Comics,-,good,61.0
9,9,Agent Bob,Male,brown,Human,Brown,178.0,Marvel Comics,-,good,81.0
10,10,Agent Zero,Male,-,-,-,191.0,Marvel Comics,-,good,104.0
11,11,Air-Walker,Male,blue,-,White,188.0,Marvel Comics,-,bad,108.0
12,12,Ajax,Male,brown,Cyborg,Black,193.0,Marvel Comics,-,bad,90.0
13,13,Alan Scott,Male,blue,-,Blond,180.0,DC Comics,-,good,90.0
14,14,Alex Mercer,Male,-,Human,-,-99.0,Wildstorm,-,bad,-99.0
15,15,Alex Woolsly,Male,-,-,-,-99.0,NBC - Heroes,-,good,-99.0
16,16,Alfred Pennyworth,Male,blue,Human,Black,178.0,DC Comics,-,good,72.0
17,17,Alien,Male,-,Xenomorph XX121,No Hair,244.0,Dark Horse Comics,black,bad,169.0
18,18,Allan Quatermain,Male,-,-,-,-99.0,Wildstorm,-,good,-99.0
19,19,Amazo,Male,red,Android,-,257.0,DC Comics,-,bad,173.0
20,20,Ammo,Male,brown,Human,Black,188.0,Marvel Comics,-,bad,101.0
21,21,Ando Masahashi,Male,-,-,-,-99.0,NBC - Heroes,-,good,-99.0
22,22,Angel,Male,blue,-,Blond,183.0,Marvel Comics,-,good,68.0
23,23,Angel,Male,-,Vampire,-,-99.0,Dark Horse Comics,-,good,-99.0
24,24,Angel Dust,Female,yellow,Mutant,Black,165.0,Marvel Comics,-,good,57.0
25,25,Angel Salvadore,Female,brown,-,Black,163.0,Marvel Comics,-,good,54.0
26,26,Angela,Female,-,-,-,-99.0,Image Comics,-,bad,-99.0
27,27,Animal Man,Male,blue,Human,Blond,183.0,DC Comics,-,good,83.0
28,28,Annihilus,Male,green,-,No Hair,180.0,Marvel Comics,-,bad,90.0
29,29,Ant-Man,Male,blue,Human,Blond,211.0,Marvel Comics,-,good,122.0
...,...,...,...,...,...,...,...,...,...,...,...
704,704,Walrus,Male,blue,Human,Black,183.0,Marvel Comics,-,bad,162.0
705,705,War Machine,Male,brown,Human,Brown,185.0,Marvel Comics,-,good,95.0
706,706,Warbird,Female,blue,-,Blond,180.0,Marvel Comics,-,good,54.0
707,707,Warlock,Male,red,-,Blond,188.0,Marvel Comics,-,good,108.0
708,708,Warp,Male,brown,-,Black,173.0,DC Comics,-,bad,67.0
709,709,Warpath,Male,brown,Mutant,Black,218.0,Marvel Comics,-,good,158.0
710,710,Wasp,Female,blue,Human,Auburn,163.0,Marvel Comics,-,good,50.0
711,711,Watcher,Male,-,-,-,-99.0,Marvel Comics,-,good,-99.0
712,712,Weapon XI,Male,-,-,-,-99.0,Marvel Comics,-,bad,-99.0
713,713,White Canary,Female,brown,Human,Black,-99.0,DC Comics,-,bad,-99.0
714,714,White Queen,Female,blue,-,Blond,178.0,Marvel Comics,-,good,65.0
715,715,Wildfire,Male,-,-,-,-99.0,DC Comics,-,good,-99.0
716,716,Winter Soldier,Male,brown,Human,Brown,175.0,Marvel Comics,-,good,117.0
717,717,Wiz Kid,-,brown,-,Black,140.0,Marvel Comics,-,good,39.0
718,718,Wolfsbane,Female,green,-,Auburn,366.0,Marvel Comics,-,good,473.0
719,719,Wolverine,Male,blue,Mutant,Black,160.0,Marvel Comics,-,good,135.0
720,720,Wonder Girl,Female,blue,Demi-God,Blond,165.0,DC Comics,-,good,51.0
721,721,Wonder Man,Male,red,-,Black,188.0,Marvel Comics,-,good,171.0
722,722,Wonder Woman,Female,blue,Amazon,Black,183.0,DC Comics,-,good,74.0
723,723,Wondra,Female,-,-,-,-99.0,Marvel Comics,-,good,-99.0
724,724,Wyatt Wingfoot,Male,brown,-,Black,196.0,Marvel Comics,-,good,117.0
725,725,X-23,Female,green,Mutant / Clone,Black,155.0,Marvel Comics,-,good,50.0
726,726,X-Man,Male,blue,-,Brown,175.0,Marvel Comics,-,good,61.0
727,727,Yellow Claw,Male,blue,-,No Hair,188.0,Marvel Comics,-,bad,95.0
728,728,Yellowjacket,Male,blue,Human,Blond,183.0,Marvel Comics,-,good,83.0
729,729,Yellowjacket II,Female,blue,Human,Strawberry Blond,165.0,Marvel Comics,-,good,52.0
730,730,Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0
731,731,Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0
732,732,Zatanna,Female,blue,Human,Black,170.0,DC Comics,-,good,57.0
733,733,Zoom,Male,red,-,Brown,185.0,DC Comics,-,bad,81.0

In [13]:
heroes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 11 columns):
Unnamed: 0    734 non-null int64
name          734 non-null object
Gender        734 non-null object
Eye color     734 non-null object
Race          734 non-null object
Hair color    734 non-null object
Height        734 non-null float64
Publisher     719 non-null object
Skin color    734 non-null object
Alignment     734 non-null object
Weight        732 non-null float64
dtypes: float64(2), int64(1), object(8)
memory usage: 63.2+ KB

In [12]:
heroes_df.describe()

       Unnamed: 0      Height      Weight
count  734.000000  734.000000  732.000000
mean   366.500000  102.254087   43.855191
std    212.031837  139.624543  130.823733
min      0.000000  -99.000000  -99.000000
25%    183.250000  -99.000000  -99.000000
50%    366.500000  175.000000   62.000000
75%    549.750000  185.000000   90.000000
max    733.000000  975.000000  900.000000

In [10]:
heroes_df.isna().any() #using method isna().any()to detect any null values in the dataframe
                        # there are two cols with missing values: Publisher and weight

Unnamed: 0    False
name          False
Gender        False
Eye color     False
Race          False
Hair color    False
Height        False
Publisher      True
Skin color    False
Alignment     False
Weight         True
dtype: bool

In [11]:
heroes_df.isna().sum() # using isna().sum() to count the numbers of null values in both columns Publisher and Weight
                       # since publisher is a categorical col,and only 15 values are missing from 734 (2%), so we will leas as is.

Unnamed: 0     0
name           0
Gender         0
Eye color      0
Race           0
Hair color     0
Height         0
Publisher     15
Skin color     0
Alignment      0
Weight         2
dtype: int64

In [18]:
weight_mean = heroes_df.Weight.mean()          #we impute null values in weight by replace null values with the mean of weight data
heroes_df = heroes_df.fillna(weight_mean)
heroes_df.isna().sum()

Unnamed: 0    0
name          0
Gender        0
Eye color     0
Race          0
Hair color    0
Height        0
Publisher     0
Skin color    0
Alignment     0
Weight        0
dtype: int64

In [17]:
powers_df.isna().any().any() # this df has no missing values. using one more any to short cut the answer

False

## Joining, Grouping, and Aggregating

In the cell below, join the two DataFrames.  Think about which sort of join you should use, as well as which columns you should join on.  Rename columns and manipulate as needed.  

**_HINT:_** If the join throws an error message, consider setting the column you want to join on as the index for each DataFrame.

In [ ]:
heroes_and_powers_df =

In the cell below, subset male and female heroes into different dataframes.  Create a scatterplot of the height and weight of each hero, with weight as the y-axis.  Plot both the male and female heroes subset into each dataframe, and make the color for each point in the scatterplot correspond to the gender of the superhero.

## Some Initial Investigation

Next, slice the DataFrame as needed and visualize the distribution of heights and weights by gender.  You should have 4 total plots.  

In the cell below:

* Slice the DataFrame into separate DataFrames by gender
* Complete the `show_distplot` function.  This helper function should take in a DataFrame, a string containing the gender we want to visualize, and and the column name we want to visualize by gender. The function should display a distplot visualization from seaborn of the column/gender combination.  

Hint: Don't forget to check the [seaborn documentation for distplot](https://seaborn.pydata.org/generated/seaborn.distplot.html) if you have questions about how to use it correctly!

In [ ]:
male_heroes_df = None
female_heroes_df = None

def show_distplot(dataframe, gender, column_name):
    pass

In [ ]:
# Male Height

In [ ]:
# Male Weight

In [ ]:
# Female Height

In [ ]:
# Female Weight

Discuss your findings from the plots above, with respect to the distribution of height and weight by gender.  Your explanation should include discussion of any relevant summary statistics, including mean, median, mode, and the overall shape of each distribution.  

Wite your answer below this line:
____________________________________________________________________________________________________________________________

### Sample Question: Most Common Powers

The rest of this notebook will be left to you to investigate the dataset by formulating your own questions, and then seeking answers using pandas and numpy.  Every answer should include some sort of visualization, when appropriate. Before moving on to formulating your own questions, use the dataset to answer the following questions about superhero powers:

* What are the 5 most common powers overall?
* What are the 5 most common powers in the Marvel Universe?
* What are the 5 most common powers in the DC Universe?

Analyze the results you found above to answer the following question:

How do the top 5 powers in the Marvel and DC universes compare?  Are they similar, or are there significant differences? How do they compare to the overall trends in the entire Superheroes dataset?

Wite your answer below this line:
____________________________________________________________________________________________________________________________


### Your Own Investigation

For the remainder of this lab, you'll be focusing on coming up with and answering your own question, just like we did above.  Your question should not be overly simple, and should require both descriptive statistics and data visualization to answer.  In case you're unsure of what questions to ask, some sample questions have been provided below.

Pick one of the following questions to investigate and answer, or come up with one of your own!

* Which powers have the highest chance of co-occurring in a hero (e.g. super strength and flight), and does this differ by gender?
* Is there a relationship between a hero's height and weight and their powerset?
* What is the distribution of skin colors amongst alien heroes?

Explain your question below this line:
____________________________________________________________________________________________________________________________



Some sample cells have been provided to give you room to work. If you need to create more cells, you can do this easily by:

1. Highlighting a cell and then pressing `esc` to enter command mode.
1. Pressing `b` to add a cell below the currently highlighted cell, or `a` to add one above it.  

Be sure to include thoughtful, well-labeled visualizations to back up your analysis!

## Summary

In this lab, we demonstrated our mastery of:
* Using all of our Pandas knowledge to date to clean the dataset and deal with null values
* Using Queries and aggregations to group the data into interesting subsets as needed
* Using descriptive statistics and data visualization to find answers to questions we may have about the data